day0:
	go run day0/parse.go day0/example.txt

day1:
	go run day1/parse.go day1/example.txt
#	go run day1/parse.go day1/input.txt

day2:
	go run day2/parse.go day2/example.txt
#	go run day2/parse.go day2/input.txt

day3:
	go run day3/parse.go day3/example.txt
#	go run day3/parse.go day3/input.txt

day4:
	go run day4/parse.go day4/example.txt
#	go run day4/parse.go day4/input.txt

day5:
	go run day5/parse.go day5/example.txt
#	go run day5/parse.go day5/input.txt

day6:
	go run day6/parse.go day6/example.txt
#	go run day6/parse.go day6/input.txt

day7:
	go run day7/parse.go day7/example.txt
#	go run day7/parse.go day7/input.txt

day8:
	go run day8/parse.go day8/example.txt
#	go run day8/parse.go day8/input.txt

day9:
	go run day9/parse.go day9/example.txt
#	go run day9/parse.go day9/input.txt

.PHONY: day0 day1 day2 day3 day4 day5 day6 day7 day8 day9
.DEFAULT_GOAL=day9
