day0:
	go run day0/parse.go day0/example.txt

day1:
	go run day1/parse.go day1/example.txt
#	go run day1/parse.go day1/input.txt

day2:
	go run day2/parse.go day2/example.txt
#	go run day2/parse.go day2/input.txt

day3:
	go run day3/parse.go day3/example.txt
#	go run day3/parse.go day3/input.txt

.PHONY: day0 day1 day2 day3
